library("ggplot2")
library("RPostgreSQL")
drv <- dbDriver("PostgreSQL")
con <- dbConnect(drv, dbname="nagios")
rs <- dbSendQuery(con,"select * from hosts order by host_count desc")
hosts <- fetch(rs, n=-1)
rs <- dbSendQuery(con, "select * from weekly")
w_i <- fetch(rs, ns=-1)
qplot(weekly_incidents, ..density.., data = w_i, geom="density", binwidth=100, xlim=c(0, 10000)) + facet_grid(quartile ~ .)
qplot(normalized_incidents, data = w_i, geom="histogram", binwidth=5, xlim=c(0, 1000)) + facet_grid(quartile ~ .)